plugins {
	id 'java'
	id 'org.springframework.boot' version '3.5.0'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'sampleBoard'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
	}
}

repositories {
	maven {
		url "https://repo1.maven.org/maven2"
	}
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-web' //web 의존성 추가
	implementation 'org.springframework.boot:spring-boot-starter-thymeleaf' //thymeleaf 의존성 추가
	runtimeOnly 'com.mysql:mysql-connector-j'        //mysql 커넥터 의존성 주입
	implementation("org.springframework.boot:spring-boot-starter-data-jpa") // JPA 의존성
	implementation 'org.springframework.boot:spring-boot-starter'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
	useJUnitPlatform()
}
